Web/Models/StatusViewModel.cs
namespace MovieNight.Models {
    public class StatusViewModel {
        public string Message { get; set; }
        public bool IsError { get; set; }
    }
}

Web/Controllers/AdminController.cs
using DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieNight.Models;
using MovieNight.Models.Admin;

namespace MovieNight.Controllers {
    public class AdminController : Controller {
        private readonly MlContext _ctx = new MlContext();

        [HttpGet]
        public IActionResult Users() {
            if (!IsAdmin()) {
                var statusModel = new StatusViewModel {IsError = true, Message = "Not authenticated"};
                return RedirectToAction("Status", "Home", statusModel);
            }

            var model = new AdminUsersViewModel();
            model.GetUsers(_ctx);

            return View(model);
        }

        [HttpGet]
        public IActionResult Submissions() {
            if (!IsAdmin()) {
                var statusModel = new StatusViewModel {IsError = true, Message = "Not authenticated"};
                return RedirectToAction("Status", "Home", statusModel);
            }

            var model = new AdminSubmissionsViewModel();
            model.GetSubmissions(_ctx);

            return View(model);
        }

        [HttpPost]
        public IActionResult Submissions(AdminSubmissionsViewModel model) {
            if (!IsAdmin()) {
                return BadRequest("Not authenticated");
            }

            if (!model.DoAction(_ctx, out var msg)) {
                return BadRequest(msg);
            }

            return Ok(msg);
        }
        
        [HttpPost]
        public IActionResult Users(AdminUsersViewModel model) {
            if (!IsAdmin()) {
                return BadRequest("Not authenticated");
            }

            if (!model.DoAction(_ctx, out var msg)) {
                return BadRequest(msg);
            }

            return Ok(msg);
        }

        public bool IsAuthenticated() {
            return HttpContext.Session.GetString("username") != null;
        }

        public bool IsAdmin() {
            return IsAuthenticated() && HttpContext.Session.GetInt32("is_admin") == 1;
        }
    }
}

Web/Controllers/ListController.cs
using DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieNight.Models;
using MovieNight.Models.List;

namespace MovieNight.Controllers {
    public class ListController : Controller {
        private readonly MlContext _ctx = new MlContext();

        [HttpGet]
        public IActionResult Watched() {
            var model = new ListViewModel();
            model.GetWatchedSubmissions(_ctx);
            return View(model);
        }

        [HttpGet]
        public IActionResult Planned() {
            var model = new ListViewModel();
            model.GetPlannedSubmissions(_ctx, GetUsername());
            return View(model);
        }

        [HttpPost]
        public IActionResult Action(ListViewModel model) {
            if (!IsAuthenticated()) {
                return BadRequest("Not authenticated");
            }
            
            if (!model.DoAction(_ctx, GetUsername(), out var msg)) {
                return BadRequest(msg);
            }

            return Ok(msg);
        }

        [HttpPost]
        public IActionResult Add(ListNewViewModel model) {
            if (!IsAuthenticated()) {
                return BadRequest("Not authenticated");
            }

            // Check if input is ok
            if (!model.Verify(out var msg)) {
                return BadRequest(msg);
            }

            // Add to database
            if (!model.AddToDb(_ctx, GetUsername(), out msg)) {
                return BadRequest(msg);
            }

            return Ok(msg);
        }

        [HttpGet]
        public IActionResult New() {
            if (!IsAuthenticated()) {
                var statusModel = new StatusViewModel {IsError = true, Message = "Not authenticated"};
                return RedirectToAction("Status", "Home", statusModel);
            }

            return View();
        }

        public bool IsAuthenticated() {
            return GetUsername() != null;
        }

        public string GetUsername() {
            return HttpContext.Session.GetString("username");
        }
    }
}

Web/Controllers/LoginController.cs
using DAL;
using DAL.Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MovieNight.Models;

namespace MovieNight.Controllers {
    public class LoginController : Controller {
        private readonly MlContext _ctx = new MlContext();
        
        [HttpGet]
        public IActionResult Index(LoginViewModel model = null) {
            if (IsAuthenticated()) {
                var statusModel = new StatusViewModel {IsError = true, Message = "Not authenticated"};
                return RedirectToAction("Status", "Home", statusModel);
            }

            return View(model);
        }
        
        [HttpGet]
        public IActionResult Logout() {
            if (!IsAuthenticated()) {
                var statusModel = new StatusViewModel {IsError = true, Message = "Not authenticated"};
                return RedirectToAction("Status", "Home", statusModel);
            }
            
            HttpContext.Session.Clear();
            var statusModel2 = new StatusViewModel {IsError = false, Message = "Successfully logged out"};
            return RedirectToAction("Status", "Home", statusModel2);
        }
        
        [HttpPost]
        public IActionResult Login(LoginViewModel model) {
            if (IsAuthenticated()) {
                var statusModel = new StatusViewModel {IsError = true, Message = "Already logged in"};
                return RedirectToAction("Status", "Home", statusModel);
            }
            
            if (!model.Login(_ctx, out var user, out var msg)) {
                var statusModel = new StatusViewModel {IsError = true, Message = msg};
                return RedirectToAction("Status", "Home", statusModel);
            }
            
            SetSession(user);
            var statusModel2 = new StatusViewModel {IsError = false, Message = msg};
            return RedirectToAction("Status", "Home", statusModel2);
        }

        private void SetSession(User user) {
            HttpContext.Session.SetString("username", user.Username);
            HttpContext.Session.SetInt32("is_admin", user.IsAdmin ? 1 : 0);
        }

        public bool IsAuthenticated() {
            return HttpContext.Session.GetString("username") != null;
        }
    }
}

Web/Views/Shared/Status.cshtml
@model StatusViewModel
@{
    ViewData["Title"] = "Status";
}


<div class="jumbotron">
    @if (Model.IsError) {
        <h1 class="display-4">Oops!</h1>
        <p class="lead">An error occurred.</p>
    } else {
        <h1 class="display-4">Info</h1>
    }
    <hr/>
    @if (Model.Message != null) {
        if (Model.IsError) {
            <p class="text-danger">@Html.DisplayFor(t => t.Message)</p>
        } else {
            <p class="text-success">@Html.DisplayFor(t => t.Message)</p>
        }
    }
</div>

Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta property="og:locale" content="en_US">
    <meta property="og:title" content="Movie Night Planner">
    <meta property="og:type" content="website">
    <meta property="og:image" content="https://movieplanner.live/logo_96.png">
    <meta property="og:description" content="Recommend and vote on movies">
    <title>@ViewBag.Title - Movie Night</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/fontawesome/all.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
              integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" 
              crossorigin="anonymous">
    </environment>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/logo_96.png" width="25" height="25" class="d-inline-block align-top" alt="">
                Movie Planner
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" 
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="List" asp-action="Planned">
                            <i class="fa fa-list"></i>
                            <span class="d-inline d-sm-none d-lg-inline">Planned</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="List" asp-action="Watched">
                            <i class="fa fa-tv"></i>
                            <span class="d-inline d-sm-none d-lg-inline">Watched</span>
                        </a>
                    </li>
                    @if (HttpContextAccessor.HttpContext.Session.GetString("username") == null) {
                        <li class="nav-item ml-sm-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">
                                <i class="fa fa-user"></i>
                                <span class="d-inline d-sm-none d-lg-inline">Log in</span>
                            </a>
                        </li>
                    } else {
                        <li class="nav-item mr-sm-auto">
                            <a class="nav-link text-dark" asp-area="" asp-controller="List" asp-action="New">
                                <i class="fa fa-edit"></i>
                                <span class="d-inline d-sm-none d-lg-inline">Add new</span>
                            </a>
                        </li>
                        if (HttpContextAccessor.HttpContext.Session.GetInt32("is_admin") == 1) {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-dark" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="fa fa-cogs"></i>
                                    <span class="d-inline d-sm-none d-xl-inline">Admin panel</span>
                                </a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="Submissions">Submissions</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" asp-controller="Admin" asp-action="Users">Users</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">
                                <i class="fa fa-user"></i>
                                Log out 
                                <span class="d-inline d-sm-none d-xl-inline">
                                    (@HttpContextAccessor.HttpContext.Session.GetString("username"))
                                </span>
                            </a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @if (ViewBag.JumbotronTitle != null) {
            <div class="jumbotron p-5">
                <div class="container">
                    <h1 class="display-4">@ViewBag.JumbotronTitle</h1>
                    @if (ViewBag.JumbotronSubTitle != null) {
                        <hr/>
                        <p class="lead">@ViewBag.JumbotronSubTitle</p>
                    }
                </div>
            </div>
        }
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year - MovieNight
    </div>
</footer>

<environment include="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
</environment>
<environment exclude="Development">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous">
    </script>
</environment>
<script src="~/js/site.js" asp-append-version="true"></script>

@RenderSection("Scripts", required: false)
</body>
</html>